all:
    hosts:
        prod:
            ansible_host: <your_server_ip>
            ansible_ssh_user: <your_server_username>
            ansible_ssh_pass: <your_server_pass>
        int:
          ansible_host: <your_server_ip>
          ansible_ssh_user: <your_server_username>
          ansible_ssh_pass: <your_server_pass>
    children:
      prod:
        ansible_host: <your_server_ip>
        ansible_ssh_user: <your_server_username>
        ansible_ssh_pass: <your_server_pass>
      int:
        ansible_host: <your_server_ip>
        ansible_ssh_user: <your_server_username>
        ansible_ssh_pass: <your_server_pass>
