all:
    hosts:
        prod:
            ansible_host: 172.30.72.228
            ansible_ssh_user: root
            ansible_ssh_pass: generic0
        int:
          ansible_host: 172.30.72.228
          ansible_ssh_user: root
          ansible_ssh_pass: generic0
    children:
      prod:
        ansible_host: 172.30.72.228
        ansible_ssh_user: root
        ansible_ssh_pass: generic0
      int:
        ansible_host: 172.30.72.228
        ansible_ssh_user: root
        ansible_ssh_pass: generic0
